#!/usr/bin/env bash

#: exec_target = cli

## Build frontend (static website)
##
## Usage: fin fe/build

# Abort if anything fails
set -e

cd ${PROJECT_ROOT}/frontend

# Contents of both .next and public have to be dropped
# Cannot use 'gatsby clean' here as it tries to drop the entry folder and we cannot do this since .next is a mounted as a volume
rm -rf .next/*
rm -rf public/*

time yarn run dev
